### ISSUE TITLE
i cant fix this error. Whats happens?

### ISSUE THREAD

**Issue by herranzraul13** [Stonley890/mc-console-bot#1]
C:\Users\Raul\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\Users\Raul\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Raul\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildChannelManager.edit (C:\Users\Raul\node_modules\discord.js\src\managers\GuildChannelManager.js:269:21)

**Comment by Stonley890** [comment]
It looks like your discord bot doesn't have the correct permissions set. Check [Step 3](https://github.com/Stonley890/mc-console-bot#3-create-a-bot) and make sure your bot has _Read Messages/View Channels_ and _Send Messages_. Then use the URL to re-invite the bot to your Discord server.

**Comment by Stonley890** [comment]
Hmm... try following this [video](https://cdn.discordapp.com/attachments/983141645115617310/997210235947204639/Demo.mp4). If it's still having issues, I'll revisit the code

**Comment by herranzraul13** [comment]
Yes yes i do it. If u want i can show you in discord. Herranzraul#8733

**Comment by Stonley890** [comment]
Fixed 2d0851990da7abcc4b2ef35b9425f8974a91b436
