### ISSUE TITLE
Error shows when typing $startserver

### ISSUE THREAD

**Issue by asdfwasfdad** [Stonley890/mc-console-bot#6]
It seems that I'm getting some errors with regard to the $startserver

Edit: I noticed that this error appears to be the same issue as the following issue: https://github.com/Stonley890/mc-console-bot/issues/5

**To Reproduce**
1. Add all details to the file
2. Start the file
3. Type $startserver

**Expected behavior**
I would expect that the bot would start up the server once the $startserver command has been sent.

**Screenshots**
![image](https://github.com/Stonley890/mc-console-bot/assets/49735352/605322d4-d56f-4e5a-bd02-709f7e221c95)
![image](https://github.com/Stonley890/mc-console-bot/assets/49735352/849bbccd-3cc0-4c68-806b-f121384bd930)
![image](https://github.com/Stonley890/mc-console-bot/assets/49735352/55109c7b-5ad6-479e-9892-ce914793b880)

**Environment (please complete the following information):**
 - OS: Windows 10
 
![image](https://github.com/Stonley890/mc-console-bot/assets/49735352/e228e0c9-e2ae-4486-a7c1-89fc30396907)

**Additional context**

Text of the error:
[2023-09-25 12:30:01] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command startserver
Traceback (most recent call last):
  File "C:\Users\Yhumm\AppData\Roaming\Python\Python311\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yhumm\Desktop\MinecraftServers\NellyATM8\mc-console-bot.py", line 57, in startserver
    if server_process.poll is None:
       ^^^^^^^^^^^^^^
NameError: name 'server_process' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Yhumm\AppData\Roaming\Python\Python311\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Yhumm\AppData\Roaming\Python\Python311\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yhumm\AppData\Roaming\Python\Python311\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'server_process' is not defined

**Comment by Stonley890** [comment]
I can't seem to reproduce the behavior, but I've pushed a new commit with a potential fix. Try the new [mc-console-bot.py](https://github.com/Stonley890/mc-console-bot/raw/main/mc-console-bot.py) and let me know what happens.

**Comment by asdfwasfdad** [comment]
That seems to have done the trick. Everything is now working perfectly well to me now. Server seems to both start and stop perfectly fine on my end.

**Comment by Stonley890** [comment]
Perfect! Thank you so much for the report.
